### ISSUE TITLE
Gintama Auto-Update Not Working

### ISSUE THREAD

**Issue by wilyub** [vosmiic/jellyfin-ani-sync#82]
I'm currently rewatching Gintama and am on Season 1 Episode 72 (S2 Episode 23 according to TVDB naming scheme). When I finished the episode, the plugin didn't update the episode on anilist. Here is the log information:

[2023-10-10 16:05:55.570 -04:00] [INF] [27] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.8.11" playing "A Dog's Paws Smell Fragrant / Drive with a \"Might\" Attitude". Stopped at "1469694" ms
[2023-10-10 16:05:55.576 -04:00] [WRN] [27] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://localhost:8096/Sessions/Playing/Stopped" to "127.0.0.1" in 0:00:01.5741719 with Status Code 204
[2023-10-10 16:05:55.589 -04:00] [INF] [29] jellyfin_ani_sync.UpdateProviderStatus: (Anidb) Anime already has AniDb ID; no need to look it up
[2023-10-10 16:05:55.590 -04:00] [INF] [29] jellyfin_ani_sync.UpdateProviderStatus: (Anidb) Anime Gintama found in anime XML file
[2023-10-10 16:05:55.591 -04:00] [INF] [29] jellyfin_ani_sync.UpdateProviderStatus: Retrieving provider IDs from offline database...
[2023-10-10 16:05:55.667 -04:00] [INF] [36] jellyfin_ani_sync.UpdateProviderStatus: Retrieved provider IDs
[2023-10-10 16:05:55.667 -04:00] [INF] [36] jellyfin_ani_sync.UpdateProviderStatus: Using provider AniList...
[2023-10-10 16:05:55.808 -04:00] [INF] [36] jellyfin_ani_sync.UpdateProviderStatus: User does not have plan to watch only ticked
[2023-10-10 16:05:55.809 -04:00] [INF] [36] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Series (Gintama) found, but provider reports episode already watched. Skipping
[2023-10-10 16:05:55.809 -04:00] [INF] [36] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Series (Gintama) found on Rewatching list
[2023-10-10 16:05:55.810 -04:00] [INF] [36] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Provider reports episode already watched; not updating
[2023-10-10 16:05:55.810 -04:00] [ERR] [36] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Could not update anime status

My anilist only has Gintama Rewatching episode 71 finished, so I believe the plugin might be trying to set episode 23 as watched? I saw in the anime master list that Gintama Episodes for Seasons 1-4 (TVDB) do have a mapping to AniDB Season 1 (201 episodes). Is there some way to use that information so that it can still map an episode S02E23 to Gintama Season 1 Episode 72? Thanks!

**Comment by vosmiic** [comment]
Unfortunately this is probably another case of different providers formatting shows in different seasons/episodes. 
But I might be able to help, what season and episode format do you have set in Jellyfin? Is it season 1 episode 72 or season 2 episode 23?

**Comment by vosmiic** [comment]
Here is the area we get the AniDB ID and we calculate the episode by using an offset (if the show is in the XML anime list): https://github.com/vosmiic/jellyfin-ani-sync/blob/f4c6fa981b42b8aa94c9bfeeb48ddc1d7a9a1ba2/Helpers/AnimeListHelpers.cs#L24-L85
Hopefully that helps.
Its difficult to make the plugin work with all of the providers we support since they seem to all use a slightly different way of numbering episodes and seasons (as you have found out).
Originally the plugin was designed for only MyAnimeList since its the service I use, so the other service's compatibility is not as strong as MAL's.
That being said its usually not an issue for shows that have generic season and episode numbering.

**Comment by vosmiic** [comment]
Sure, will investigate this. Planning on starting up development again of the plugin now as there are quite a few things to look at, and will make this one of them. Thanks for the detailed analysis, will make implementing any changes much faster.
I'll keep you updated on the progress 👍

**Comment by KaXaSA** [comment]
I guess I'm having the same issue, but with One Piece, everything else works as intended. (didn't test Gintama)

I use Sonarr to deal with metadata, folder, file management, and my folders/files look like this:
```
    One Piece (1999)
    ├── Season 21
    │   ├── One Piece (1999) - S21E185 - 1076 - Episode_Title.mkv
```
**1076** = episode absolute number

I'm not sure if this useful information, but this is how I tested it:
1. Open Anilist, change the _Episode Progress_ to **1**
2. Open Jellyfin and mark as _watched_: **Season 21 > Episode 185**
3. Log:
```
[INF] [75] jellyfin_ani_sync.UpdateProviderStatus: (Anidb) Anime already has AniDb ID; no need to look it up
[INF] [75] jellyfin_ani_sync.UpdateProviderStatus: (Anidb) Anime One Piece found in anime XML file
[INF] [75] jellyfin_ani_sync.UpdateProviderStatus: Retrieving provider IDs from offline database...
[INF] [80] jellyfin_ani_sync.UpdateProviderStatus: Retrieved provider IDs
[INF] [80] jellyfin_ani_sync.UpdateProviderStatus: Using provider AniList...
[INF] [80] jellyfin_ani_sync.UpdateProviderStatus: User does not have plan to watch only ticked
[INF] [80] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Series (ONE PIECE) found on Plan_to_watch list
[INF] [80] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Updated series (ONE PIECE) progress to 185
```
So it changed the _Episode Progress_ in Anilist to 185 instead of **1076**

**Comment by SolarWolf-Code** [comment]
@KaXaSA do you mind sending your Sonarr Anime Episode Format that you got it working with?

**Comment by KaXaSA** [comment]
> @KaXaSA do you mind sending your Sonarr Anime Episode Format that you got it working with?

Sadly, I actually didn't get it working at all, you would need to manually change the metadata or create a script to do a search & replace on the metadata files to change the season of all the episodes to 1.

I don't think you can change the file format nor any other option in Sonarr to easily fix this.

**Comment by SolarWolf-Code** [comment]
> > @KaXaSA do you mind sending your Sonarr Anime Episode Format that you got it working with?
> 
> Sadly, I actually didn't get it working at all, you would need to manually change the metadata or create a script to do a search & replace on the metadata files to change the season of all the episodes to 1.
> 
> I don't think you can change the episode format nor any other option in Sonarr to easily fix this.

Okay some good news. I think I've got something working :))

Here are the steps:
## Set Sonarr Anime Episode Format

We can actually force Sonarr to name the episode S01 every time. You'll notice instead of using something more traditional such as `S{season:00}` we use `S01`. You can simply paste this into the `Anime Episode Format` located at `Settings > Media Management`.

`{Series TitleYear} - S01E{absolute:000} - {Episode CleanTitle} [{Custom Formats }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}[{MediaInfo VideoBitDepth}bit]{[MediaInfo VideoCodec]}[{Mediainfo AudioCodec} { Mediainfo AudioChannels}]{MediaInfo AudioLanguages}{-Release Group}`

This results in a naming scheme like this:
```
Single Episode: The Series Title! (2010) - S01E001 - Episode Title 1 [HDTV-720p v2][HLG][10bit][x264][DTS 5.1][JA]-RlsGrp
Multi Episode: The Series Title! (2010) - S01E001-003 - Episode Title [HDTV-720p v2][HLG][10bit][x264][DTS 5.1][JA]-RlsGrp
```

There are a few other things that I have setup to make this work. Firstly, we need to make sure and select `Anime` as the series type:  
![image](https://github.com/vosmiic/jellyfin-ani-sync/assets/54452723/54826d98-3cb3-4cd4-9da7-869d75fd5790)
That will force the format above.   

I also like having season folders. The directory structure will look like this:  
```
Gintama (2006) [tvdbid-79895]/
├── Season 01
│   ├── Gintama (2006) - S01E001-002 - You Guys!! Do You Even Have Gintama!! [HDTV-1080p][10bit][x265][Opus 2.0][JA]-Judas.mkv
│   ├── Gintama (2006) - S01E003 - Nobody with Naturally Wavy Hair Can Be That Bad [HDTV-1080p][10bit][x265][Opus 2.0][JA]-Judas.mkv
│   └── Gintama (2006) - S01E004 - Watch Out! Weekly Shonen JUMP Sometimes Comes Out on Saturdays! [HDTV-1080p][10bit][x265][Opus 2.0][JA]-Judas.mkv
└── Season 02
    ├── Gintama (2006) - S01E050 - Pending Means Pending Its Not Final [HDTV-1080p][10bit][x265][Opus 2.0][JA]-Judas.mkv
    ├── Gintama (2006) - S01E051 - Milk Should Be Served at Body Temperature [HDTV-1080p][10bit][x265][Opus 2.0][JA]-Judas.mkv
    └── Gintama (2006) - S01E052 - If You Want to See Someone Make an Appo First [HDTV-1080p][10bit][x265][Opus 2.0][JA]-Judas.mkv
```

## How it appears in Jellyfin  
The season folders properly show up:  
![image](https://github.com/vosmiic/jellyfin-ani-sync/assets/54452723/4d7894cb-a3c0-435b-8f18-b93192007936)
And the metadata is properly filled in:  
![image](https://github.com/vosmiic/jellyfin-ani-sync/assets/54452723/d4366025-d9dd-424e-a4c1-961ef89aa9ee)
Season 2 title will appear as absolute episode numbers:  
![image](https://github.com/vosmiic/jellyfin-ani-sync/assets/54452723/bdde7e62-9385-4401-9a8d-0c27037ba9c9)

## Testing it with AniList  
Firstly, make sure that you have this plugin "safely" set up. To do so, ensure that you have the following option ticked:  
![image](https://github.com/vosmiic/jellyfin-ani-sync/assets/54452723/4c4987c2-0202-4efa-897c-2a3ca5bec6da)

After we watch episode 23 of Season 2, absolute episode 72 (A Dog's Paws Smell Fragrant / Drive with a "Might" Attitude) we can see the plugin properly set the episode as watched:  
![image](https://github.com/vosmiic/jellyfin-ani-sync/assets/54452723/d5e4004c-3d9d-464f-ace5-e48034b87e1d)

**Comment by KaXaSA** [comment]
@SolarWolf-Code Try to test that with some newer anime, to see if it will display the proper episode information for seasons 2+

**Comment by SolarWolf-Code** [comment]
@KaXaSA I've tried with Jujutsu Kaisen as well but I'll give another few a try :))

**Comment by KaXaSA** [comment]
@SolarWolf-Code I tested with some stuff I have here, everything seems to works fine on jellyfin, but One Piece specifically still doesn't work with the ani-sync plugin:
```
...
[22:33:03] [INF] [26] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Series (ONE PIECE) found on Plan_to_watch list
[22:33:03] [INF] [26] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Provider reports episode already watched; not updating
[22:33:03] [ERR] [26] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Could not update anime status
```

**Comment by SolarWolf-Code** [comment]
Well it seemed to have worked for Gintama but it doesn't seem to be working for some other anime. Despite the episodes being in separate season folders, the metadata seems to be filling the season based on the name. Not only this but, sometimes AniSync sends a request past the amount of episodes:
![image](https://github.com/vosmiic/jellyfin-ani-sync/assets/54452723/9b4a2cf4-3a12-4442-a879-d6103790559a)

The way AniList splits the anime is what can cause problems. For long running shows without breaks they will have a single entry for it. Although for a show like AoT that is not the case

**Comment by KaXaSA** [comment]
> Do you have `Automatically set completed shows as rewatching?` ticked? I'm not 100% sure but the logs suggest its because you have it already watched?

Nah, that's not it, I don't even have that episode marked as watched in Anilist, when I tested this the last time, I changed the episode progress to 1 in Anilist, then in Jellyfin I marked S21E185 (absolute: 1076) as watched, and the ani-sync plugin updated the anime progress to episode 185 (instead of 1076).

> A possible solution to this is use the different formats. Such as Standard for your standard shows, Anime for split up shows, and Daily as long running shows. Really not sure this is a good method though...

I tried to use standard like that, but it turns out that standard is only good for series it doesn't work well with anime, maybe it could work with Daily (it just doesn't have the {absolute...} format), but I suspect this won't fix the issue with One Piece because the plugin will probably use the information in the metadata file instead of using the filename, and in the metadata it still uses the TVDB season format.

Jellyfin does have a AniDB metadata plugin I wonder if that could help, I recall that I tested this in the past and had some issue that made me disable it and just use Sonarr instead.

**Comment by vosmiic** [comment]
Now that I am looking at this again, I have had a look at the code I am found some interesting notes. Probably didn't think of these earlier as I haven't worked in this specific area of the plugin for some time.

> I think the logic I would use for determining the exact Anilist/MAL entry would be as follows:
> 
>     * Find TVDB ID & Season number (Should be in the Jellyfin Metadata).
> 
>     * Go to anime-list.xml and find all entries that have a matching TVDB ID.
> 
>     * * If the list is size 1, then use the old logic and we're done.
> 
>     * * If the list is size > 1, then iterate through the entries by looking at the "defaulttvdbseason" category in the "anime" node.
> 
>     * * * If the season number matches the entry, use that AniDB ID and then follow the old logic. We're done.
> 
>     * * * If the season number is "a" (absolute ordering), then go into the "mapping-list" node and iterate through the seasons there until you find a matching season. (Example: Fairy Tail (2014)). Once you confirm the season # is in there, use the AniDB from the parent "anime" node and follow old logic. We're done.

It is actually already doing this (for TVDB IDs), in a slightly different way. 
On these lines (I understand you have limited exposure to C#, so I have attempted to explain how it works below):
https://github.com/vosmiic/jellyfin-ani-sync/blob/55b5dc8dc189338c9f7b4cab37874e25fbcae1ce/Helpers/AnimeListHelpers.cs#L73-L81
We are looking up the anime in the XML, iterating through the results and finding which AniDB entry the current episode belongs to.
So if you were watching episode 200 of Fairy Tail, it would assume you are watching "Fairy Tail (2014)" and send back `9980` as the AniDB ID, which is correct.
Since we don't use the TVBD ID with the [API database](https://github.com/BeeeQueue/arm-server), we can disregard it.
I think the root of your original problem is that you probably have a **mixture of AniDB and TVDB metadata in your library entries** (not a problem on your end, can't blame you for having _too much_ metadata and the plugin should be able to deal with it). 
So I believe that your library layout (seasons and episodes) is using the TVDB format, while each entry has AniDB metadata.
>This leads me to believe that the plugin is only looking at the AniDB ID/TVDB ID for the original Gintama Season without looking at the season

Not quite, but you aren't exactly incorrect. We do use the season number but it doesn't have much importance when looking up the AniDB entry in the XML, since the AniDB entry shouldn't depend on the season. Each AniDB entry is its own season (or at least should be), hence why the plugin prefers to use it over TVDB (which as you know likes to throw everything into a single TVDB entry).
So the plugin gets confused; it doesn't care you are watching episode 200, it sees you have an AniDB ID in your metadata so it can simply look up the ID and return the only result  (also if there is more than one entry in the XML list with the same AniDB ID the plugin falls back to other metadata providers if they exist). So @KaXaSA you are pretty much spot on with
>So that explains the Provider reports episode already watched; not updating it's ignoring the season and using the episode number as if it were the absolute episode number

because it shouldn't _need_ to look up seasons.

This needs changing, for these occasions, as you have outlined.
Perhaps looking up the entry via the AniDB, checking if there are other entries that have the same TVDB ID. 
Then compare the offsets of the entries and get the AniDB of the correct entry.
This sounds very similar to your original suggested logic changes @wilyub so apologies if I am basically reiterating it, but just wanted to voice my findings.
That being said, I would suggest (for now) perhaps removing either the TVDB or AniDB metadata providers (and forcing a refresh (and select "Replace all metadata" for the refresh mode) of Gintama so the seasons/episodes get shuffled around in Jellyfin) as they obviously don't work well together and see if that fixes things. I would suggest using the AniDB metadata provider if you can, it generally works a bit better with the plugin. If you do decide to remove one of these metadata providers and refresh your metadata, please do let us know how you get on. If it fixes your issues its probably a good idea to let others know that using these two metadata providers at the same time causes issues. The wiki page [here](https://github.com/vosmiic/jellyfin-ani-sync/wiki/Metadata-Downloader-Compatibility) needs updating to reflect this, it hasn't changed since we overhauled how we detect anime.

Also thanks guys for digging quite deep into this to work out where the plugin needs improvements, if you have found anything that I haven't or believe any of what I have said above is incorrect please do correct me/let me know, like I said this is some old code so I may have missed something.

**Comment by KaXaSA** [comment]
Yeah, same here:
```
[00:32:06] [INF] [15] jellyfin_ani_sync.UpdateProviderStatus: (Tvdb) Anime reference found in anime list XML
[00:32:06] [INF] [15] jellyfin_ani_sync.UpdateProviderStatus: Retrieving provider IDs from offline database...
[00:32:06] [INF] [42] jellyfin_ani_sync.UpdateProviderStatus: Retrieved provider IDs
[00:32:06] [INF] [42] jellyfin_ani_sync.UpdateProviderStatus: Using provider AniList...
[00:32:07] [INF] [42] jellyfin_ani_sync.UpdateProviderStatus: User does not have plan to watch only ticked
[00:32:07] [INF] [42] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Series (ONE PIECE) found on Plan_to_watch list
[00:32:07] [INF] [42] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Updated series (ONE PIECE) progress to 187
```

Just as an example, S21E187 metadata:
```
<episodedetails>
  <title>He Returns! The Shogun of Wano Country, Kozuki Momonosuke</title>
  <season>21</season>
  <episode>187</episode>
  <aired>2023-10-01</aired>
  <plot>The people of the Flower Capital get flustered when Kin’emon and the other Akazaya samurai who were supposed to be dead appear from the smoke. However, the last one who walks out of the smoke, and what he says, confuses the people even more.</plot>
  <uniqueid type="tvdb" default="true">10024785</uniqueid>
  <uniqueid type="sonarr">1851</uniqueid>
  <thumb>https://artworks.thetvdb.com/banners/v4/episode/10024785/screencap/6518d86b9e6ce.jpg</thumb>
  <watched>false</watched>
  <fileinfo>
    <streamdetails>
      <video>
        <aspect>1.7777778</aspect>
        <bitrate>0</bitrate>
        <codec>x264</codec>
        <framerate>23.976023976023976023976023976</framerate>
        <height>1080</height>
        <scantype>Progressive</scantype>
        <width>1920</width>
        <duration>23.847666666666665</duration>
        <durationinseconds>1431</durationinseconds>
      </video>
      <audio>
        <bitrate>0</bitrate>
        <channels>2</channels>
        <codec>AAC</codec>
        <language>jpn</language>
      </audio>
      <subtitle>
        <language>eng</language>
      </subtitle>
    </streamdetails>
  </fileinfo>
</episodedetails>
```

**Comment by SolarWolf-Code** [comment]
@vosmiic Use mention you suggestion using AniDB as the metadata provider, do you happen to know how that would work out with Sonarr?

As far as I know, Sonarr will treat these shows as a single entry because they use TVDB as their metadata provider. But AniDB would create different show entries for such as AoT (I believe it's something like 8 different entries). Any ideas? I'm more than willing to test with my selection of shows if I can get a naming scheme work :))

**Comment by KaXaSA** [comment]
The idea would probably be:
### Sonarr
Disable the Metadata file creation (Settings ⇾ Metadata)

### Jellyfin 
 1. Add the AniDB metadata plugin 
 1. anime library > manage library: 
\- enable only 'AniDB' as your 'metadata downloaders' (all of them)
\- enable 'Nfo' in Metadata savers
 1. Then go back and do a library scan using the replacing all metadata option.

With that, I expect:

A. Sonarr should probably still do its folder/file management magic, renaming stuff as intended.
B. Jellyfin should completely replace all the metadata files using the AniDB as the provider.
C. Ani Sync should now work with no issues.

I actually want to test this, but like I said, I think I already tried this before, and there was some issue with the AniDB plugin, but I don't remember what was the issue 🤡, I may still give this a shot on the weekend, not sure yet.

**Comment by vosmiic** [comment]
>I did a quick test on Gintama by only having TVDB metadata and unfortunately it still didn't work.

Thats a shame, but thanks for testing it out.

I have tested using only the AniDB and it still isn't working unfortunately, so I wouldn't suggest @KaXaSA changing your  metadata settings just yet. Don't want to accidentally cause your library to break.

>@vosmiic Use mention you suggestion using AniDB as the metadata provider, do you happen to know how that would work out with Sonarr?

I'm not sure honestly, in my development environment I don't use Sonarr so its hard to tell on my side. I would presume Jellyfin will be able to map to the AniDB format even if Sonarr transforms the files and folders into the TVDB format, but I would probably hold off since I don't actually think it would fix anything as stated above.

I will attempt to implement the potential solution outlined in my previous comment and let you guys know how I get on.

**Comment by vosmiic** [comment]
So I am able to calculate the absolute episode number (unfortunately the Jellyfin API does not provide it) by simply iterating through the seasons and getting a count of the total episodes up to the one being watched, which we can use to compare to the offset and get the correct AniDB ID.
The only issue with this method is that it relies on the series being complete. The absolute episode number will be incorrect otherwise.
For example if you only had season 1, 2, 3 and 7 of Gintama (according to TVDB) and watched an episode in season 7, the plugin would only count the episodes in season 1, 2 and 3 to get the offset because they are the only seasons available to the plugin. Which would probably give you an absolute episode number of an episode in season 4.
I'm thinking this is probably a niche issue as I would presume most users would keep a full library, but its enough to make me wonder if there is a better way of approaching this.

**Comment by SolarWolf-Code** [comment]
@vosmiic There definitely is a better way. And I'm working on a Python script that I'll send here and you can try to translate it to C#. I'm almost done, but I think we have all the info we need

**Comment by vosmiic** [comment]
Thanks @wilyub for the suggestions, might have found a minor issue with the code:

`if (foundAnime.Count() == 1) return int.TryParse(foundAnime.First().Anidbid, out aniDbId) ? (aniDbId, null) : (null, null); `
Unfortunately I don't think this will always work, as it is dependant on your metadata providers. In my case Gintama is separated into 10 seasons (due to the TVDB metadata), and only the series contains the AniDB ID (which represents the first season). So this should probably be extended to `if (foundAnime.Count() == 1 && season == 1)`. We could also do a lookup of the accurate AniDB ID via the TVDB ID and offset search if it contains it.

The rest could definitely work and are good ideas, if we decide the absolute episode number potential being incorrect because of the reason explained in this [comment](https://github.com/vosmiic/jellyfin-ani-sync/issues/82#issuecomment-1831111039)  is acceptable. Thanks again for the suggestion.

**Comment by vosmiic** [comment]
>Any ideas on shows like One Piece/Detective Conan that don't have seasons in the mapping list?

Hmm I'm not sure. Unfortunately there may be some shows that we simply will not be able to support. I guess the best course of action would be to implement a solution for the majority of situations and then investigate if we can support the niche cases.

**Comment by KaXaSA** [comment]
What if you had a plugin option where the user could pick between using TVDB OR AniDB? 
Would that be an _easier said than done_ situation, or are there other reasons for not going that route?

**Comment by vosmiic** [comment]
>What if you had a plugin option where the user could pick between using TVDB OR AniDB?

The issue is more the fact that Jellyfin doesn't bother storing some necessary metadata if TVDB or AniDB is higher on the metadata priority list than the other; if TVDB is higher, than we lose a significant amount of AniDB metadata because of the formatting. I presume this also happens the other way around. We would have to forcibly tell users to use one or the other as their primary metadata provider to ensure we get all of the necessary metadata.

So I have been able to reliably get the AniDB ID by using a mixture of season number and episode offset lookups; it was successfully able to get the AniDB IDs for all of the seasons of Gintama.
The only issue now is that when I look up that ID using the offline database, no provider IDs are returned. This kind of completely stops me in my tracks because we completely rely on the API data.

For example, I was testing on season 9 (depending on where you look) of Gintama, which has an AniDB ID of [13263](https://anidb.net/anime/13263). But when I attempt to lookup (https://relations.yuna.moe/api/ids?source=anidb&id=13263) the related provider IDs for the entry, all fields are null.

I presume this is because it is spread across 2 seasons on most providers, as you can see from the list of resources on AniDB. MyAnimeList has it across https://myanimelist.net/anime/35843 and https://myanimelist.net/anime/36838.

And as far as I can tell the AniDB API is very difficult to work with, basically unusable, so its not really an option. Also they do not like people scraping the raw HTML page.

Going to investigate a different way to approach the issue and will keep you guys updated on my progress.

**Comment by vosmiic** [comment]
After looking a bit further into the issue, it seems it may only be season 7 of Gintama that is having issues because it is spread across multiple entities in MyAnimeList and AniList; this may also be the case for a few other shows, but as it is this improves working with shows spread across multiple seasons by a decent margin.

From a brief test, the solution that we have come up with will mean that it will correctly update the progress for all seasons of Gintama apart from season 7. Not a perfect solution but at least quite a bit better than how the plugin currently works.

I will also need to test it using a few other shows but I would have thought we would see similar results to Gintama.

**Comment by vosmiic** [comment]
So development work is mostly complete, the changes have not yet been merged to master though. Wondered if anyone was able to do some basic testing using their library to see if it is working for them, I have tested in my limited development library and all seems to be working but obviously more testing is always welcome and would be much appreciated, but obviously don't feel pressured to do so.

It should be as stable as the current release version of the plugin in terms of not ruining your Jellyfin environment, but since I have changed the areas that detect what anime you are watching it might be best to keep an eye on the log to make sure it hasn't updated something incorrectly.

Also feel free to use any combination of metadata providers, hopefully what I have implemented means that it isn't dependent on specific providers.

Here is the dll file (its in a zip because GitHub won't let me upload a raw dll file): [jellyfin-ani-sync.zip](https://github.com/vosmiic/jellyfin-ani-sync/files/13593422/jellyfin-ani-sync.zip)

Or if you would prefer, you can build off of this branch: https://github.com/vosmiic/jellyfin-ani-sync/tree/anime-detection-changes

Thanks.

**Comment by KaXaSA** [comment]
I just replaced the plugins\Ani-Sync_2.9.0.0\jellyfin-ani-sync.dll with the one in the zip file without changing anything else, not sure if that's ok.

Tested with:
One Piece (1999) - S21E188 - 1079 - Episode Title.mkv

```
[22:32:07] [INF] [86] jellyfin_ani_sync.UpdateProviderStatus: (Tvdb) Anime reference found in anime list XML
[22:32:07] [WRN] [86] jellyfin_ani_sync.UpdateProviderStatus: (AniDb) Could not lookup using absolute episode number, falling back to season number lookup
[22:32:07] [INF] [86] jellyfin_ani_sync.UpdateProviderStatus: (Tvdb) Anime One Piece could not found in anime XML file; falling back to other metadata providers if available...
[22:32:07] [INF] [86] jellyfin_ani_sync.UpdateProviderStatus: Using provider AniList...
[22:32:07] [INF] [83] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Found matching series: ONE PIECE
[22:32:07] [INF] [83] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Attempting to get season 1...
[22:32:07] [INF] [83] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Could not find any related anime
[22:32:07] [WRN] [83] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Could not find next season
```

> How many seasons do you currently have in your Jellyfin library...
I also just keep a few episodes in Jellyfin, having all seasons is pretty rare.

( Happy Holidays 🥳)

**Comment by vosmiic** [comment]
>You are right that I only have Aggretsuko S5 in my library.

This should be sorted now, basically wasn't handling the case of not having the entire series in the library.

As for the issues you are seeing @KaXaSA, what metadata do you have on your One Piece entry in Jellyfin? What AniDB ID and/or TVDB ID does the series have? Odd that it isn't able to do a simple ID match.

Thanks both for testing, will upload a new dll file with the fixes once I have confirmed its sorted out all of the found issues.

**Comment by KaXaSA** [comment]
> what metadata do you have on your One Piece entry in Jellyfin? What AniDB ID and/or TVDB ID does the series have? Odd that it isn't able to do a simple ID match.

(removed unnecessary metadata info)

Serie metadata 
```
...
  <title>One Piece</title>
  <id>81797</id>
  <uniqueid type="tvdb" default="true">81797</uniqueid>
  <uniqueid type="imdb">tt0388629</uniqueid>
...
```

Episode metadata
```
...
<season>21</season>
  <episode>188</episode>
  <uniqueid type="tvdb" default="true">10073293</uniqueid>
  <uniqueid type="sonarr">2447</uniqueid>
...
```

I checked the metadata in Jellyfin too, just to make sure, and it matches these .nfo files.

**Comment by vosmiic** [comment]
Thanks @KaXaSA, back to looking at this. Will hopefully have some improvements out soon, I'll keep you guys updated.

**Comment by vosmiic** [comment]
So I have created a [new version](https://github.com/vosmiic/jellyfin-ani-sync/files/13853981/jellyfin-ani-sync.zip) that should sort out the issues of not having the entire show in your library.
As for the issues with Aggretsuko @wilyub, I can see that it won't recognise season 5 because its not in the XML file yet. I tested it with season 4 and it seems to be working.
And @KaXaSA I think the way the plugin currently works it won't find One Piece because it can't calculate the offset as it hasn't got all of the episodes, and it can't fall back to looking up by season number because the XML file only has a single season but multiple entries in the XML file (the specials). I'll investigate if there are other ways of still reliably detecting the anime in the XML file in these cases.

**Comment by vosmiic** [comment]
Looked a bit more into it, read a bit more into how the anime list XML is formatted and I don't think its possible to map to a show that is formatted in Jellyfin in the aired order and is not complete. I think the XML can be a bit confusing sometimes, as some entries contain aired order and others are absolute.
Perhaps adding a clause to the metadata comparability page stating that the plugin works best at detecting shows when the series is fully present in Jellyfin.

**Comment by vosmiic** [comment]
So these changes are now in a beta release, which can be added to your local environment by [adding the new beta manifest](https://github.com/vosmiic/jellyfin-ani-sync#development). Like the readme states, both repos can be used at the same time, and any new stable releases will replace the beta releases and vice versa when they become available. 

Don't worry about participating in the beta release if you aren't comfortable with it, if no issues are found it will be promoted to stable in a few weeks once a decent amount of testing has been done. Going to close the PR but it can be re-opened if issues related to it are found. Thanks
